name: Skip Clean (originally by reidab)
description: Skips cleaning on checkout
author: https://github.com/xdevs23
requirements: []
configuration:
  properties:
    cd:
      type: string
  required: []
